config/routes.rb
Rails.application.routes.draw do
  devise_for :hosts
  resources :events

  root 'static#welcome'

  get 'about' => 'static#about'
  get 'success' => 'static#success'

  resources :subscribers, only: [:new, :create]
  resources :communities, only: [:new, :create]

  get '/join' => 'subscriber#new'

  as :host do
    get "/login" => "devise/sessions#new"
  end

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :subscribers
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :host
  belongs_to :community
  validates_presence_of :title
  validates_presence_of :date_and_time
  validates_presence_of :location
  validates_presence_of :community_id

  scope :later_than_today, lambda{ where("date_and_time > ?", Date.today) }
end

app/models/host.rb
class Host < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  belongs_to :community
  validate :mobile_or_email_provided?

  def mobile_or_email_provided?
    if mobile.blank? && email.blank?
      errors[:base] << "You must provide either a mobile number or email"
    end
  end
end

app/models/twilio.rb
require 'twilio-ruby'

module TwilioSender
  def self.send_sms(subscribers, message)
    account_sid = ENV['twilio_sid']
    auth_token = ENV['twilio_auth_token']
    client = Twilio::REST::Client.new account_sid, auth_token

    from = ENV['twilio_number']

    subscribers.each do |subscriber|
      client.account.messages.create(
        :from => from,
        :to => subscriber,
        :body => message
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    new_event_path
  end
end

app/controllers/events_controller.rb
require 'twilio-ruby'

class EventsController < ApplicationController
  def index
    @events = Event.later_than_today.order(:date_and_time)
  end

  def new
    @event = Event.new
  end

  def create
    community = Community.find(params[:event][:community_id])
    @event = community.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'You have set up an event, and all members of your community have been automatically notified via email and/or SMS.' }

        message = "You are invited to #{@event.title} on #{@event.date_and_time.to_formatted_s(:short)} at #{@event.location}."

        message += " Women only, please." if @event.female_only
        message += " Children are welcome." if @event.children_welcome
        message += " Childcare will be provided." if @event.childcare

        mobile_numbers = community.subscribers.pluck('mobile')

        send_sms(mobile_numbers, message)
      else
        format.html { render :new }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :location, :community_id, :female_only, :children_welcome, :childcare, :date_and_time)
  end

  def send_sms(subscribers, message)
    account_sid = ENV['twilio_sid']
    auth_token = ENV['twilio_auth_token']
    client = Twilio::REST::Client.new account_sid, auth_token

    from = ENV['twilio_number']

    subscribers.each do |subscriber|
      client.account.messages.create(
        :from => from,
        :to => subscriber,
        :body => message
      )
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:host).permit(:name, :mobile, :email, :password, :password_confirmation)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
  end

  def host_event
  end

  def success
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
    @subscriber = Subscriber.new
  end

  def create
    community = Community.find(params[:subscriber][:community_id])
    @subscriber = community.subscribers.new(subscriber_params)
    if @subscriber.save
      redirect_to success_path
    else
      render 'new'
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :mobile, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def translateBoolean(bool)
    bool == true ? '<span class="glyphicon glyphicon-ok"></span>' : '<span class="glyphicon glyphicon-remove"></span>'  
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.text_field :title, autofocus: true, placeholder: "Event name", class: 'form-control'
  .form-group
    = f.text_field :location, autofocus: true, placeholder: "Location", class: 'form-control'
  .form-group
    = f.collection_select :community_id, Community.all, :id, :name, {prompt: "Select your community"}, {class: 'form-control'}
  .form-group
    = f.datetime_select :date_and_time, :minute_step => 30
  .form-group
    = f.check_box :female_only
    = f.label :female_only
  .form-group
    = f.check_box :children_welcome
    = f.label :children_welcome
  .form-group
    = f.check_box :childcare
    = f.label :childcare
  .actions
    = f.submit "Create", class: 'btn btn-large'
    = f.label "By clicking this button you will invite everybody in your community"

app/views/events/edit.html.haml
%h1 Editing event
= render 'form'
= link_to 'Show', @event
|
= link_to 'Back', events_path

app/views/events/index.html.haml
.container
  .row
    .col-md-12
      %h1 All active events
      %table
        %thead
          %tr
            %th{:colspan => "3"}
        %tbody
          - if @events.any?
            %table.table.tableHeader
              %thead
                %tr
                  %td
                    Event title
                  %td
                    Location
                  %td
                    Date and time
                  %td
                    Female Only
                  %td
                    Children Welcome
                  %td
                    Childcare
            - @events.each do |event|
              %table.table
                %thead
                  %tr
                    %td
                      = event.title
                    %td
                      = event.location
                    %td
                      = event.date_and_time.to_formatted_s(:short)
                    %td
                      = translateBoolean(event.female_only).html_safe
                    %td
                      = translateBoolean(event.children_welcome).html_safe
                    %td
                      = translateBoolean(event.childcare).html_safe

app/views/events/new.html.haml
.container
  .row
    .col-md-6
      %h3 Invite the community to your events. Build up your attendees list to keep in touch.

      = render 'form'

app/views/events/show.html.haml
.container
  .row
    .col-md-6
      %h1
        #notice= notice

app/views/layouts/_footer.html.haml
.footer-content
  This is an open-source project created during
  = link_to "Empower Hack 2015.", "http://www.empowerhack.com/"
  Get involved on 
  = link_to "Github", "https://github.com/empowerhack/Marhaba"

app/views/layouts/_header.html.haml
%h1
  = link_to (image_tag "logo.svg", :id => "main-logo"), root_path
  = link_to "About", about_path, class: 'btn btn-link pull-right', :id => "about-button"
  = link_to "Events Near You", events_path, class: 'btn btn-link pull-right', :id => "about-button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RefugeeHackProject
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.page-header
      = render partial: 'layouts/header'
    %main.content
      - if flash && flash.to_hash["alert"].present?
        - flash.each do |name, msg|
          = content_tag :div, msg, class: 'alert alert-info'
      = yield
    %footer
      = render partial: 'layouts/footer'

app/views/subscribers/new.html.haml
.container
  .row
    .col-md-6
      %h3 Tell us about yourself, so we can invite you to camp meetings that are useful for you.

      = form_for @subscriber do |f|
        - if @subscriber.errors.any?
          - @subscriber.errors.full_messages.each do |error|
            = error

        .form-group
          = f.text_field :name, autofocus: true, placeholder: 'name', class: 'form-control'
        .form-group
          = f.email_field :email, autofocus: true, placeholder: 'email', class: 'form-control'
        .form-group
          = f.text_field :mobile, autofocus: true, placeholder: 'mobile number', class: 'form-control'
        .form-group
          = f.collection_select :community_id, Community.all, :id, :name, {prompt: "Select your community"}, {class: 'form-control'}
        .actions
          = f.submit "Sign up", class: 'btn btn-large'